name: publish app

on:
  push:
    branches: ["main"]
    paths:
     - 'src/**'
  pull_request:
    branches: ["main"]
    paths:
     - 'src/**'

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  CONTAINER_NAME: todo_app
  IMAGE_NAME: ilya-games/todo_app:latest

jobs:
  publish:
    name: publish docker image
    runs_on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login ghcr.io
      run: |
        echo ${{ secrets.PAT }} |
        docker login ${{ env.REGISTRY }} --username ${{ env.OWNER }} --password-stdin
    - name: build app image
      run: |
        docker compose build ${{ env.CONTAINER_NAME }}
    - name: publish app image
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 
